#:schema node_modules/wrangler/config-schema.json
name = "billing-system-task"
main = "src/index.ts"
compatibility_date = "2024-10-11"


# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
 binding = "BILLING_KV"
 id = "cd89fd2da48a4000b12ff0dd52989cee"

 [[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "billing_system"
database_id = "aa58161b-6b6f-4fe3-ae21-3807990e5339"


[triggers]
crons = ["0 * * * *", "*/30 * * * *"]  # First cron runs every hour, second cron runs every 30 minutes